### ISSUE TITLE
toggle directory fold ('zx') after leaving tree view crashes vifm

### ISSUE THREAD

**Issue by Markuzcha** [vifm/vifm#856]
Following steps to reproduce the bug:
- :tree depth=2 (depth=2 is important as the issue doesn't occur with :tree only or with other depth)
- go with cursor to subfolder in next depth level
- open it with 'l' key (-> implicitly leaving the tree view)
- go back with 'h' key
- toggle directory fold with 'zx' keymap
- vifm crashes with the following error message:
  - "vifm: filelist.c:3002: flist_toggle_fold: Zusicherung »curr->folded == (state == FOLD_USER_CLOSED || state == FOLD_AUTO_CLOSED) && "Metadata is not in sync."« nicht erfüllt."
 
![Screenshot_2022-12-27 23-37-31](https://user-images.githubusercontent.com/6181015/209735226-df170519-a328-4784-a98d-1aefa2cc7803.png)
![Screenshot_2022-12-27 23-37-39](https://user-images.githubusercontent.com/6181015/209735228-f6262dfd-cffd-4d6d-8b99-6dcd0ae3f55f.png)
![Screenshot_2022-12-27 23-37-44](https://user-images.githubusercontent.com/6181015/209735229-522192bd-4a40-4f9d-97e5-c54f31ed06ed.png)
![Screenshot_2022-12-27 23-37-48](https://user-images.githubusercontent.com/6181015/209735230-54a48bd1-b7d0-49ef-bc18-8a4dab721bca.png)
![Screenshot_2022-12-27 23-37-58](https://user-images.githubusercontent.com/6181015/209735231-2161928d-f197-43b0-bc73-a829ea10aae7.png)

**Comment by haolian9** [comment]
I can reproduce it (but not with 100% chance) on vifm master on linux, here are some backtraces of the crash on my machine:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `vifm . .'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
Downloading 0.00 MB source file /usr/src/debug/glibc/nptl/pthread_kill.c
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
[Current thread is 1 (Thread 0x7f50e9f9e740 (LWP 58687))]
>>> bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f50ea08b6b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f50ea03b958 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f50ea02553d in __GI_abort () at abort.c:79
#4  0x00007f50ea02545c in __assert_fail_base (fmt=0x7f50ea19fa50 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x555d3bf2fc38 "curr->folded == (state == FOLD_USER_CLOSED || state == FOLD_AUTO_CLOSED) && \"Metadata is not in sync.\"", file=0x555d3bf2f6c3 "filelist.c", line=2999, function=<optimized out>) at assert.c:92
#5  0x00007f50ea034486 in __GI___assert_fail (assertion=assertion@entry=0x555d3bf2fc38 "curr->folded == (state == FOLD_USER_CLOSED || state == FOLD_AUTO_CLOSED) && \"Metadata is not in sync.\"", file=file@entry=0x555d3bf2f6c3 "filelist.c", line=line@entry=2999, function=function@entry=0x555d3bf2fd90 <__PRETTY_FUNCTION__.2> "flist_toggle_fold") at assert.c:101
#6  0x0000555d3bef0160 in flist_toggle_fold (view=0x555d3bf7b600 <rwin>) at filelist.c:2999
#7  0x0000555d3be54360 in execute_mapping_handler (key_info=..., keys_info=keys_info@entry=0x7ffdefd226e0, info=0x555d3c862300) at engine/keys.c:1312
#8  0x0000555d3be55819 in dispatch_key (key_info=..., keys_info=keys_info@entry=0x7ffdefd226e0, curr=curr@entry=0x555d3c8622f0, keys=keys@entry=0x7ffdefd227b8 L"") at engine/keys.c:742
#9  0x0000555d3be54ce0 in execute_next_keys (curr=curr@entry=0x555d3c8622f0, keys=keys@entry=0x7ffdefd227b8 L"", key_info=key_info@entry=0x7ffdefd22650, keys_info=keys_info@entry=0x7ffdefd226e0, has_duplicate=<optimized out>, no_remap=no_remap@entry=0) at engine/keys.c:708
#10 0x0000555d3be55264 in dispatch_keys_at_root (keys=0x7ffdefd227b8 L"", keys@entry=0x7ffdefd227b0 L"zx", keys_info=keys_info@entry=0x7ffdefd226e0, root=<optimized out>, key_info=..., no_remap=no_remap@entry=0) at engine/keys.c:512
#11 0x0000555d3be555cd in dispatch_keys (keys=<optimized out>, keys@entry=0x7ffdefd227b0 L"zx", keys_info=keys_info@entry=0x7ffdefd226e0, no_remap=no_remap@entry=0, prev_count=-1) at engine/keys.c:394
#12 0x0000555d3be55741 in execute_keys_general (keys=0x7ffdefd227b0 L"zx", timed_out=timed_out@entry=0, mapped=mapped@entry=0, no_remap=no_remap@entry=0) at engine/keys.c:361
#13 0x0000555d3be560a4 in execute_keys_general_wrapper (mapped=0, no_remap=0, timed_out=0, keys=keys@entry=0x63944e63acccfc00 <error: Cannot access memory at address 0x63944e63acccfc00>) at engine/keys.c:341
#14 vle_keys_exec (keys=keys@entry=0x7ffdefd227b0 L"zx") at engine/keys.c:309
#15 0x0000555d3bee949c in event_loop (quit=quit@entry=0x555d3bf389f4 <quit>, manage_marking=manage_marking@entry=1) at event_loop.c:263
#16 0x0000555d3bf16dd4 in vifm_main (argc=<optimized out>, argv=<optimized out>) at vifm.c:365
#17 0x0000555d3be463f9 in main (argc=<optimized out>, argv=<optimized out>) at vifm.c:120

>>> frame 6
#6  0x0000555d3bef0160 in flist_toggle_fold (view=0x555d3bf7b600 <rwin>) at filelist.c:2999
2999            assert(curr->folded == (state == FOLD_USER_CLOSED ||

>>> list
2994            char full_path[PATH_MAX + 1];
2995            get_full_path_of(curr, sizeof(full_path), full_path);
2996
2997            FoldState state = get_fold_state(view->custom.folded_paths, full_path);
2998
2999            assert(curr->folded == (state == FOLD_USER_CLOSED ||
3000                                    state == FOLD_AUTO_CLOSED) && "Metadata is not in sync.");
3001
3002            switch(state)
3003            {
>>>
```

**Comment by xaizek** [comment]
Thanks for the report!

**Comment by Markuzcha** [comment]
Thank your guys for this wonderful file manager!

(I'm starting to use it as my main one now.
Dragged and dropped the screenshots in here with dragon-drop after elegantly search selecting them with :select // ...what a beauty!)

**Comment by Markuzcha** [comment]
Nice !
